### ISSUE TITLE
Errors when 0.3.10 call stop command

### ISSUE THREAD

**Issue by Slach** [rtshome/pgrepup#15]
```
  pgsql-proxy: ++ pgrepup -c /etc/pgrepup/pgrepup_pgsql1.conf stop
  pgsql-proxy: Pgrepup 0.3.10
  pgsql-proxy: Traceback (most recent call last):
  pgsql-proxy:   File "/usr/local/bin/pgrepup", line 25, in <module>
  pgsql-proxy:
  pgsql-proxy: main()
  pgsql-proxy:   File "/usr/local/lib/python2.7/dist-packages/pgrepup/cli.py", line 64, in main
  pgsql-proxy:
  pgsql-proxy: dispatch(__doc__)
  pgsql-proxy:   File "/usr/local/lib/python2.7/dist-packages/pgrepup/helpers/docopt_dispatch.py", line 39, in __call__
  pgsql-proxy:
  pgsql-proxy: function(**self._kwargify(arguments))
  pgsql-proxy: TypeError
  pgsql-proxy: :
  pgsql-proxy: stop() takes no arguments (14 given)
```
